<div class="navbar navbar-default" id="navbar-second">
    <div class="navbar-boxed">

        <ul class="nav navbar-nav no-border visible-xs-block">
            <li>
                <a class="text-center collapsed" data-toggle="collapse" data-target="#navbar-second-toggle"><i class="icon-menu7"></i></a>
            </li>
        </ul>

        <div class="navbar-collapse collapse" id="navbar-second-toggle">
            <ul class="nav navbar-nav">

                <li><a href="/"><i class="icon-display4 position-left"></i></a></li>

                <li class="dropdown mega-menu active- mega-menu-wide- hide">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Vendas
                        <span class="caret"></span></a>

                    <div class="dropdown-menu dropdown-content width-400">
                        <div class="dropdown-content-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <span class="menu-heading underlined">Serviços</span>
                                    <ul class="menu-list">
                                        <li><a href="/contracts/">Contratos</a></li>
                                    </ul>
                                </div>
                                <div class="col-md-6">
                                    <span class="menu-heading underlined">Cadastros</span>
                                    <ul class="menu-list">
                                        <li class="active-"><a href="/customers/">Clientes</a></li>
                                        <li><a href="/services/">Serviços</a></li>
                                        <li><a href="/plans/">Planos</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>

                <li class="dropdown mega-menu">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
                        ERP
                        <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu width-200">

                        <li><a href="/customers/">Clientes</a></li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Saas</a>
                            <ul class="dropdown-menu">
                                <li><a href="/saas/">Serviços</a></li>
                                <li><a href="/saascontractsintest/">Contratos em teste</a></li>
                                <li><a href="/saascontracts/">Contratos</a></li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Financeiro</a>
                            <ul class="dropdown-menu">
                                <li><a href="/bills/">Faturas</a></li>
                                <li><a href="/paymenttransactions/">Transações de pagamentos</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Atendimentos</a></li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documentação</a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Documentação</a></li>
                                <li><a href="#">Releases</a></li>
                                <li><a href="#">Vídeos</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Bugs e sugestões</a></li>
                            </ul>
                        </li>
                        <li class="divider"></li>
                        <li><a href="/cron/">Tarefas</a></li>
                    </ul>
                </li>

                <li class="dropdown mega-menu mega-menu-wide- hide">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Cadastros <span
                                class="caret"></span></a>

                    <div class="dropdown-menu dropdown-content width-300">
                        <div class="dropdown-content-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <span class="menu-heading underlined hide">Serviços SaaS</span>
                                    <ul class="menu-list">

                                        <li><a href="/prospects/">Prospects</a></li>
                                        <li><a href="/customers/">Clientes</a></li>
                                        <li><a href="/bills/">Faturas</a></li>
                                        <li><a href="/saas/">Saas - Serviços</a></li>
                                        <li><a href="/saascontracts/">Saas - Contratos</a></li>

                                    </ul>
                                </div>
                                <div class="col-md-6 hide">
                                    <span class="menu-heading underlined">Serviços SaaS</span>
                                    <ul class="menu-list">
                                        <li><a href="#">Clientes</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>

                <li class="dropdown mega-menu mega-menu-wide- hide">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Financeiro
                        <span class="caret"></span></a>

                    <div class="dropdown-menu dropdown-content width-300">
                        <div class="dropdown-content-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <span class="menu-heading underlined">Movimentações</span>
                                    <ul class="menu-list">
                                        <li><a href="#">Faturas</a></li>
                                    </ul>
                                </div>
                                <div class="col-md-6 hide">
                                    <span class="menu-heading underlined">Cadastros</span>
                                    <ul class="menu-list">
                                        <li><a href="#">Clientes</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>

                <li class="dropdown hide-">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
                        Starter kit <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu width-200">
                        <li class="dropdown-header">Basic layouts</li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-grid2"></i>
                                Columns</a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header highlight">Options</li>
                                <li><a href="1_col.html">One column</a></li>
                                <li><a href="2_col.html">Two columns</a></li>
                                <li class="dropdown-submenu">
                                    <a href="#">Three columns</a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-header highlight">Sidebar position</li>
                                        <li><a href="3_col_dual.html">Dual sidebars</a></li>
                                        <li><a href="3_col_double.html">Double sidebars</a></li>
                                    </ul>
                                </li>
                                <li><a href="4_col.html">Four columns</a></li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-paragraph-justify3"></i>
                                Navbars</a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header highlight">Fixed navbars</li>
                                <li><a href="layout_navbar_fixed_main.html">Fixed main navbar</a></li>
                                <li><a href="layout_navbar_fixed_secondary.html">Fixed secondary navbar</a></li>
                                <li><a href="layout_navbar_fixed_both.html">Both navbars fixed</a></li>
                            </ul>
                        </li>
                        <li class="dropdown-header">Optional layouts</li>
                        <li class="active-"><a href="layout_boxed.html"><i class="icon-align-center-horizontal"></i>
                                Fixed width</a></li>
                        <li><a href="layout_sidebar_sticky.html"><i class="icon-flip-vertical3"></i> Sticky sidebar</a>
                        </li>
                    </ul>
                </li>

            </ul>

            <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">

                    <a href="/admin/settings/" class="btn-tip dropdown-toggle-" data-tip="Acesse as configurações gerais da aplicação" data-toggle-="dropdown" data-hover="dropdown">
                        Configurações
                        <i class="icon-cog3 hide"></i>
                        <span class="visible-xs-inline-block position-right">Dropdown</span>
                        <span class="caret hide"></span>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-right">
                        <li><a href="#">Tarefas</a></li>
                    </ul>

                </li>
            </ul>
        </div>
    </div>
</div>