<?php
?>
<div class="row">
    <div class="col-3">
        <a class="btn btn-light d-block mb-2 text-left" href="#" onclick="FwSendFilePrint('/samples/sendfiles/send','id=999&add=ABC');">imprimir 1 arquivo</a>
        <a class="btn btn-light d-block mb-2 text-left" href="#" onclick="FwSendFileDownload('/samples/sendfiles/send');">download 1 arquivo</a>
        <a class="btn btn-light d-block mb-2 text-left" href="#" onclick="FwSendFileEmail('/samples/sendfiles/send');">enviar 1 arquivo email</a>
        <a class="btn btn-light d-block mb-2 text-left" href="#" onclick="FwSendFileWhatsapp('/samples/sendfiles/send');">enviar 1 arquivo whatsapp</a>
        <hr>
        <a class="btn btn-light d-block mb-2 text-left" href="#" onclick="FwSendFilePrint('/samples/sendfiles/send-many');">imprimir varios arquivos</a>
        <a class="btn btn-light d-block mb-2 text-left" href="#" onclick="FwSendFileDownload('/samples/sendfiles/send-many');">download varios arquivos</a>
        <a class="btn btn-light d-block mb-2 text-left" href="#" onclick="FwSendFileEmail('/samples/sendfiles/send-many');">enviar varios arquivos email</a>
        <a class="btn btn-light d-block mb-2 text-left" href="#" onclick="FwSendFileWhatsapp('/samples/sendfiles/send-many');">enviar varios arquivos whatsapp</a>
        <hr>
        <a class="btn btn-light d-block mb-2 text-left" href="#" onclick="FwSendFile('/samples/sendfiles/send-many');">seleciona a acao no arquivo</a>
    </div>
</div>
