<div class="panel panel-default">
    <div class="panel-heading">
        Notificações
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">

                <ul class="list-unstyled-">
                    <li><a href="title">title</a></li>
                    <li><a href="titlebuttons">title with buttons</a></li>
                    <li><a href="viewheaderfooter">adiciona views no cabecalho e rodape</a></li>
                    <li><a href="sample">breadcrumb - exemplo simples</a></li>
                    <li><a href="alterhome">breadcrumb - alterar a URL do link raiz (inicial)</a></li>
                    <hr>
                    <li><a href="addcss">adicionando arquivo .css ao layout</a></li>
                    <li><a href="addjs">adicionando arquivo .js ao layout</a></li>
                    <li><a href="addjscode">adicionando código javascript ao layout</a></li>

                </ul>

            </div>

        </div>
    </div>
</div>