<div class="panel panel-default">
    <div class="panel-body">

        <div class="row">
            <div class="col-md-8">
                <ul>

                    <h3>FORM</h3>
                    <li><a href="form1">model db</a></li>
                    <li><a href="form2">model em uma classe</a></li>
                    <li><a href="form3">saveAndBack desativado</a></li>
                    <li><a href="form4?id=1">pegando os dados - model db</a></li>
                    <li><a href="form5?id=1">pegando os dados - model em uma classe</a></li>
                    <hr>

                    <h3>LIST e FORM</h3>
                    <li><a href="list1">model db</a></li>
                    <li>TODO:model array</li>
                    <li><a href="list3">model em uma classe</a></li>
                    <li><a href="list4">listagem dos dados em uma view (nao em uma tabela)</a></li>
                    <li><a href="list5">janela modal</a></li>
                    <li><a href="list6">model db com um select adicional</a></li>
                    <li><a href="list7">welcome</a></li>
                    <li><a href="list8">menu de acoes</a></li>
                    <li><a href="list9">botao adicional no cabeçalho</a></li>
                    <li><a href="list10">busca simples</a></li>
                    <li>TODO:busca avancada</li>
                    <li><a href="list15">inclui registro com id</a></li>
                    <hr>

                    <h3>EXTRAS</h3>
                    <li><a href="listsub1?id=1">form com sublist (listagem dentro do formulário)</a></li>
                    <li><a href="info1">exibir informacoes</a></li>
                    <li><a href="resume1">exibir resumo</a></li>
                    <li><a href="js1">setando arquivo javascript</a></li>
                    <li>TODO:<a href="#">desligar header e footer</a></li>

                </ul>

            </div>

            <div class="col-md-4">
            </div>

        </div>
    </div>
</div>
