<div class="row">
    <div class="col-md-6">

        <div class="card">
            <div class="card-body">
            <ul class="list list-unstyled mb-0">

                <li><a href="/samples/zend-framework/">Zend Framework</a></li>
                <li>JavaScript
                    <ul>
                        <li><a href="/samples/js/">Geral</a>
                        <li><a href="/samples/js/ajax-get-post/">Ajax - GET e POST</a>
                        <li><a href="/samples/js/modal/">Janela Modal</a>
                        <li><a href="/samples/js/modal-get-post/">Janela Modal - GET e POST</a>
                        <li><a href="/samples/js/block/">Block</a>
                        <li><a href="/samples/js/notification/">Notificações</a>
                    </ul>
                </li>

                <li><a href="/samples/uploads/">FwUploads</a></li>
                <li><a href="/samples/sendfiles/">SendFiles</a></li>

                <hr>
                <li><a href="/samples/layout/" class="text-muted">TODO: FwLayout</a></li>
                <li><a href="/samples/form/" class="text-muted">TODO: FwForms</a></li>
                <li><a href="/samples/table/" class="text-muted">TODO: FwTable</a></li>
                <li><a href="/samples/listform/" class="text-muted">TODO: FwListform</a></li>
                <li><a href="/samples/uploadattach/" class="text-muted">TODO: FwAttachments</a></li>

            </ul>
        </div>
        </div>

    </div>
    <div class="col-md-6">

        <div class="card">
            <div class="card-body">
            <ul class="list list-unstyled mb-0">

                <li class="list-group-item-">ViewHelpers Lib
                    <ul>
                        <li><a href="/samples/view-helper/fw-format-value/">FwFormatValue</a></li>
                        <li><a href="/samples/view-helper/fw-badge/">FwBadge</a></li>
                        <li>FwPanels
                            <ul>
                                <li><a href="/samples/view-helper/fw-panels/?id=1">Exemplo 1</a>
                                <li><a href="/samples/view-helper/fw-panels/?id=2">Exemplo 2</a>
                                <li><a href="/samples/view-helper/fw-panels/?id=3">Exemplo 3</a>
                                <li><a href="/samples/view-helper/fw-panels/?id=4">Exemplo 4</a>
                                <li><a href="/samples/view-helper/fw-panels/?id=5">Exemplo 5</a>
                            </ul>
                        </li>
                        <li><a href="/samples/view-helper/fw-tabs/">FwTabs</a></li>
                        <li>FwWizard
                            <ul>
                                <li><a href="/samples/view-helper/fw-wizard/?id=1&add=ABC">Exemplo 1</a>
                            </ul>
                        </li>

                        <li><a href="/samples/view-helper/fw-buttons/">FwButtons</a></li>
                        <li><a href="/samples/view-helper/fw-buttons-card/">FwButtonsCard</a></li>
                        <li><a href="/samples/view-helper/fw-titles/">FwTitles</a></li>

                        <hr>
                        <li><a href="/samples/view-helper/#/" class="text-muted">TODO: FwMediaList</a></li>
                        <li><a href="/samples/view-helper/#/" class="text-muted">TODO: FwFeed</a></li>
                        <li><a href="/samples/view-helper/#/" class="text-muted">TODO: FwLinkTo</a></li>
                        <li><a href="/samples/view-helper/#/" class="text-muted">TODO: FwSection</a></li>
                        <li><a href="/samples/view-helper/#/" class="text-muted">TODO: FwColumns</a></li>
                        <li><a href="/samples/view-helper/#/" class="text-muted">TODO: \Fw\Lib\FwForm\ElementSearch</a></li>

                    </ul>
                </li>


            </ul>
        </div>
        </div>

    </div>
</div>

