<?php

$txt = \Fw\Lib\FwHelper::getSampleStrings('lorem_ipsum');
$txt = substr($txt, 0, 160);

// media 1 /////////////////////////////////////////////////////////////////////////////////////////////////////////////

$panelHeading = new \Fw\ViewHelper\Widgets\FwPanelHeading();
$panelHeading->setTitle('Lista 1');

$mediaList = new \Fw\ViewHelper\Widgets\FwMediaList();

for ($i = 1; $i <= 3; $i++) {

    $mediaItem = new \Fw\ViewHelper\Widgets\FwMediaListItem();
    $mediaItem->setBody($txt);
    $mediaItem->setBodyTitle('Title test', true, true);
    #$mediaItem->setLeft("<i class=\"icon-file-play text-warning-400 icon-2x no-edge-top mt-5\"></i>");
    $mediaItem->setRight("<span class=\"label label-danger\">{$i}</span>");
    #$mediaItem->setButton($panelBody3Buttons);
    #$mediaItem->setLink('lnk-tmp',$i);

    $mediaList->add($mediaItem);

}

$panel = new \Fw\ViewHelper\Widgets\FwPanel();
$panel->add($panelHeading);
$panel->add($mediaList);

$html1 = $panel->getHTML();

unset($panelHeading, $mediaList, $mediaItem, $panel);

// media 2 /////////////////////////////////////////////////////////////////////////////////////////////////////////////

$panelButtons = new \Fw\ViewHelper\Widgets\FwButtons();
$panelButtons->setDropdownIcon();
$panelButtons->addButtonDropdown('Editar', 'btn-edit-tmp');
$panelButtons->addButtonDropdown('Excluir', 'btn-edit-tmp');

$panelHeading = new \Fw\ViewHelper\Widgets\FwPanelHeading();
$panelHeading->setTitle('Lista 2');

$mediaList = new \Fw\ViewHelper\Widgets\FwMediaList();

for ($i = 1; $i <= 3; $i++) {

    $mediaItem = new \Fw\ViewHelper\Widgets\FwMediaListItem();
    $mediaItem->setBody($txt);
    #$mediaItem->setBodyTitle('Title test', true, true);
    $mediaItem->setLeft("<i class=\"icon-file-play text-warning-400 icon-2x no-edge-top mt-5\"></i>");
    #$mediaItem->setRight("<span class=\"label label-danger\">{$i}</span>");
    $mediaItem->setButton($panelButtons);
    #$mediaItem->setLink('lnk-tmp',$i);

    $mediaList->add($mediaItem);

}

$panel = new \Fw\ViewHelper\Widgets\FwPanel();
$panel->add($panelHeading);
$panel->add($mediaList);

$html2 = $panel->getHTML();

?>

<div class="row">
    <div class="col-md-6">
        <?php echo $html1 ?>
    </div>
    <div class="col-md-6">
        <?php echo $html2 ?>
    </div>
</div>

<?php

$txt = \Fw\Lib\FwHelper::getSampleStrings('lorem_ipsum');
$txt = substr($txt, 0, 160);

// media 3 /////////////////////////////////////////////////////////////////////////////////////////////////////////////

$panelHeading = new \Fw\ViewHelper\Widgets\FwPanelHeading();
$panelHeading->setTitle('Lista 3 - com links');

$mediaList = new \Fw\ViewHelper\Widgets\FwMediaList();
$mediaList->setLinked()->setBordered();

for ($i = 1; $i <= 3; $i++) {

    $mediaItem = new \Fw\ViewHelper\Widgets\FwMediaListItem();
    $mediaItem->setBody($txt);
    $mediaItem->setBodyTitle('Title test', true, true);
    #$mediaItem->setLeft("<i class=\"icon-file-play text-warning-400 icon-2x no-edge-top mt-5\"></i>");
    $mediaItem->setRight("<span class=\"status-mark bg-danger\"></span>");
    #$mediaItem->setButton($panelBody3Buttons);
    $mediaItem->setLink('lnk-tmp', $i);

    $mediaList->add($mediaItem);

}

$panel = new \Fw\ViewHelper\Widgets\FwPanel();
$panel->add($panelHeading);
$panel->add($mediaList);

$html1 = $panel->getHTML();

unset($panelHeading, $mediaList, $mediaItem, $panel);

// media 4 /////////////////////////////////////////////////////////////////////////////////////////////////////////////

$panelHeading = new \Fw\ViewHelper\Widgets\FwPanelHeading();
$panelHeading->setTitle('Lista 4 - com anotaçoes');

$mediaList = new \Fw\ViewHelper\Widgets\FwMediaList();
$mediaList->setLinked();
$mediaList->setAnnotationType($mediaList::ANNOTATION_HEADER_RIGHT);

for ($i = 1; $i <= 3; $i++) {

    $mediaItem = new \Fw\ViewHelper\Widgets\FwMediaListItem();
    $mediaItem->setBody($txt);
    $mediaItem->setBodyTitle('Title test', true, true);
    #$mediaItem->setLeft("<i class=\"icon-file-play text-warning-400 icon-2x no-edge-top mt-5\"></i>");
    #$mediaItem->setRight("<span class=\"status-mark bg-danger\"></span>");
    #$mediaItem->setButton($panelBody3Buttons);
    $mediaItem->setLink('lnk-tmp', $i);
    $mediaItem->setAnnotation(time());

    $mediaList->add($mediaItem);

}

$panel = new \Fw\ViewHelper\Widgets\FwPanel();
$panel->add($panelHeading);
$panel->add($mediaList);

$html2 = $panel->getHTML();

unset($panelHeading, $mediaList, $mediaItem, $panel);

?>

<div class="row">
    <div class="col-md-6">
        <?php echo $html1 ?>
    </div>
    <div class="col-md-6">
        <?php echo $html2 ?>
    </div>
</div>


<?php

$txt = \Fw\Lib\FwHelper::getSampleStrings('lorem_ipsum');
$txt = substr($txt, 0, 160);

// media 5 /////////////////////////////////////////////////////////////////////////////////////////////////////////////

$panelHeading = new \Fw\ViewHelper\Widgets\FwPanelHeading();
$panelHeading->setTitle('Lista 5 - com links');

$mediaList = new \Fw\ViewHelper\Widgets\FwMediaList();
$mediaList->setLinked()->setBordered();

$panelButtons = new \Fw\ViewHelper\Widgets\FwButtons();
$panelButtons->setDropdownIcon();
$panelButtons->addButtonDropdown('Editar', 'btn-edit-tmp');
$panelButtons->addButtonDropdown('Excluir', 'btn-edit-tmp');

for ($i = 1; $i <= 3; $i++) {

    $mediaItem = new \Fw\ViewHelper\Widgets\FwMediaListItem();
    $mediaItem->setBody($txt);
    $mediaItem->setBodyTitle('Title test', true, true);
    #$mediaItem->setLeft("<i class=\"icon-file-play text-warning-400 icon-2x no-edge-top mt-5\"></i>");
    $mediaItem->setRight("<span class=\"status-mark bg-danger\"></span>");
    $mediaItem->setButton($panelButtons);
    $mediaItem->setLink('lnk-tmp', $i);

    $mediaList->add($mediaItem);

}

$panel = new \Fw\ViewHelper\Widgets\FwPanel();
$panel->add($panelHeading);
$panel->add($mediaList);

$html1 = $panel->getHTML();

unset($panelHeading, $mediaList, $mediaItem, $panel);

// media 6 /////////////////////////////////////////////////////////////////////////////////////////////////////////////

$panelHeading = new \Fw\ViewHelper\Widgets\FwPanelHeading();
$panelHeading->setTitle('Lista 4 - com anotaçoes');

$mediaList = new \Fw\ViewHelper\Widgets\FwMediaList();
$mediaList->setLinked();
$mediaList->setAnnotationType($mediaList::ANNOTATION_HEADER_RIGHT);

for ($i = 1; $i <= 3; $i++) {

    $mediaItem = new \Fw\ViewHelper\Widgets\FwMediaListItem();
    $mediaItem->setBody($txt);
    $mediaItem->setBodyTitle('Title test', true, true);
    #$mediaItem->setLeft("<i class=\"icon-file-play text-warning-400 icon-2x no-edge-top mt-5\"></i>");
    #$mediaItem->setRight("<span class=\"status-mark bg-danger\"></span>");
    #$mediaItem->setButton($panelBody3Buttons);
    $mediaItem->setLink('lnk-tmp', $i);
    $mediaItem->setAnnotation(time());

    $mediaList->add($mediaItem);

}

$panel = new \Fw\ViewHelper\Widgets\FwPanel();
$panel->add($panelHeading);
$panel->add($mediaList);

$html2 = $panel->getHTML();

unset($panelHeading, $mediaList, $mediaItem, $panel);

?>

<div class="row">
    <div class="col-md-6">
        <?php echo $html1 ?>
    </div>
    <div class="col-md-6">
    </div>
</div>
