<div class="panel panel-default">
    <div class="panel-heading">
        exemplo completo - upload e lista
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <?= $this->html1 ?>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        lista os anexos
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <?= $this->html2 ?>
            </div>
        </div>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">
        lista os anexos - forma alternativa
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <?= $this->html3 ?>
            </div>
        </div>
    </div>
</div>


