<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">

                <ul class="list">
                    <li><a href="tests">testes</a></li>
                    <li>testes fileuploader
                        <ul>
                            <li><a href="tests-fileuploader-1">fileuploader 1 - um arquivo, imagens jpg</a></li>
                            <li><a href="tests-fileuploader-2">fileuploader 2 - vários arquivos, imagens jpg e png</a></li>
                            <li><a href="tests-fileuploader-avatar">fileuploader 3 - avatar</a></li>
                        </ul>
                    </li>
                    <li><a href="fwform">componente upload</a></li>
                </ul>

            </div>

        </div>
    </div>
</div>
