<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle( $this->APP_NAME )->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('assetssite/css/style.css'))
                        ->prependStylesheet($this->basePath('assetssite/css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('assetssite/css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php $this->headScript()
            ->prependFile($this->basePath('assetssite/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assetssite/js/jquery-2.2.4.min.js'))
        ?>
        <?= $this->headScript() ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('site-home') ?>">
                        <img src="<?= $this->basePath('assetssite/img/zf-logo.png') ?>" alt="<?= $this->APP_NAME ?>"/>&nbsp;<?= $this->APP_NAME ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('site-home') ?>">Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                site/view/layout/site/layout <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
