<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">

                <h1></h1>
                <ul class="list-unstyled-">
                    <li><a href="simples">simples</a></li>
                    <li><a href="noheader">sem cabeçalho</a></li>
                    <li><a href="checkbox">com checkbox</a></li>
                    <li><a href="urledit">com link para editar</a></li>
                    <li><a href="btnfunctiondelete">com botão de função padrão (delete)</a></li>
                    <li><a href="btnfunction">com botões de função personalizados</a></li>
                    <li><a href="menuaction">com menu de ações</a></li>
                    <li><a href="firstlast">class first, last</a></li>
                    <li><a href="centerrightleft">alinhamento center, right, left das colunas</a></li>
                    <li><a href="formatfields">formatação das colunas: date, datetime, double, money, int</a></li>
                    <li><a href="helperclassfields">helper class das colunas: bold, active, font-mini, font-gray</a></li>
                    <hr>
                    <li><a href="#">TODO: abre quadro resumo</a></li>
                    <li><a href="#">TODO: com order</a></li>
                    <li><a href="#">TODO: com group</a></li>
                    <li><a href="#">TODO: campo active destacado (class)</a></li>
                    <li><a href="#">TODO: com menu de ações dropdown em HTML</a></li>
                </ul>

            </div>

        </div>
    </div>
</div>