<div class="panel panel-default">
    <div class="panel-body">

        <div class="row">
            <div class="col-md-8">

                <h1></h1>
                <ul>
                    <li><a href="input">input elements</a></li>
                    <li><a href="gethtmlformcollection">get html form with formcollection</a></li>
                    <li><a href="gethtmlformrender">get html form with render</a></li>
                    <li><a href="gethtmlformbs">get html form with bootstrap form-group</a></li>
                    <li><a href="setdata">set data form</a></li>
                    <li><a href="binddata">bind data form</a></li>
                    <li><a href="validate">validate form</a></li>
                    <li><a href="disableinput">disable subject input</a></li>
                    <li><a href="disablerequired">disable name required input</a></li>
                    <li><a href="appform">appform</a></li>
                    <hr>
                    <li><a href="fwformview">form com elementos do FwForm mas sendo rendedirado em uma view</a></li>
                    <li><a href="fwformrender">form com elementos do FwForm e send renderizado pela classe</a></li>
                    <li><a href="formajax">form com o post via ajax</a></li>
                    <hr>
                    <li><a href="masks">mascaras</a></li>
                    <li><a href="select2">select2</a></li>
                </ul>

            </div>

            <div class="col-md-4">
            </div>

        </div>
    </div>
</div>
