<?php

// FORM ////////////////////////////////////////////////////////////////

$form = new \Fw\Lib\FwForm\FwForm();
$form->setAttribute('class', 'form-modal');

/* @var \Fw\ViewHelper\FwForm $formRender */

$name = new \Fw\Lib\FwForm\ElementText('name');
$name->setLabel('Nome',true);
$name->setGridColumns(12)->startGridRow()->endGridRow();
$form->addElement($name);

$formRender = $this->ViewFwForm();
#$formRender->setFormTagsOpenClose(false);
$formRender->setForm($form);

#$form->populateValues($this->data);

echo $formRender->render();
